# Generated by Django 4.2.2 on 2024-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='data_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='dob'),
        ),
    ]
