# Generated by Django 4.2.2 on 2024-01-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_customers_data_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='data_of_birth',
            new_name='dob',
        ),
    ]
