# Generated by Django 4.2.2 on 2024-01-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_data_of_birth_customers_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='backend_api.customers'),
        ),
    ]
