# Generated by Django 4.2.2 on 2024-01-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_insurancepolicy_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='policy_type',
            new_name='type',
        ),
    ]
