# Generated by Django 4.2.2 on 2024-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_rename_policy_type_insurancepolicy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='cover',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
