# Generated by Django 4.2.2 on 2024-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_insurancepolicy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('accident', 'Accident')], max_length=20),
        ),
    ]
